# TPR

In [12]:
from imbal.metrics import TPR

test_metric = TPR()
print(test_metric.name)
test_metric.update_state([1, 1, 0, 0], [1, 1, 1, 0])
test_metric.result()

tpr


<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

# FPR

In [13]:
from imbal.metrics import FPR

test_metric = FPR()
print(test_metric.name)
test_metric.update_state([1, 1, 0, 0], [1, 1, 1, 0])
test_metric.result()

fpr


<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

# TNR

In [14]:
from imbal.metrics import TNR

test_metric = TNR()
print(test_metric.name)
test_metric.update_state([1, 1, 0, 0], [1, 1, 1, 0])
test_metric.result()

tnr


<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

# Precision

In [15]:
from imbal.metrics import Precision

test_metric = Precision()
print(test_metric.name)
test_metric.update_state([1, 1, 0, 0], [1, 1, 1, 0])
test_metric.result()

precision


<tf.Tensor: shape=(), dtype=float64, numpy=0.6666666666666666>

# Expected TP

In [16]:
from imbal.metrics import ExpectedTP

test_metric = ExpectedTP()
print(test_metric.name)
test_metric.update_state([1, 1, 0, 0], [1, 1, 1, 0])
test_metric.result()

expected_tp


<tf.Tensor: shape=(), dtype=float64, numpy=1.5>

# Expected TN

In [17]:
from imbal.metrics import ExpectedTN

test_metric = ExpectedTN()
print(test_metric.name)
test_metric.update_state([1, 1, 0, 0], [1, 1, 1, 0])
test_metric.result()

expected_tn


<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

# Expected Correct

In [18]:
from imbal.metrics import ExpectedCorrect

test_metric = ExpectedCorrect()
print(test_metric.name)
test_metric.update_state([1, 1, 0, 0], [1, 1, 1, 0])
test_metric.result()

expected_correct


<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

# TSS

In [19]:
from imbal.metrics import TSS

test_metric = TSS()
print(test_metric.name)
test_metric.update_state([1, 1, 0, 0], [1, 1, 1, 0])
test_metric.result()

tss


<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

# HSS

In [20]:
from imbal.metrics import HSS

test_metric = HSS()
print(test_metric.name)
test_metric.update_state([1, 1, 0, 0], [1, 1, 1, 0])
test_metric.result()

hss


<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

# Gilbert Skill Score (GS)

In [21]:
from imbal.metrics import GS

test_metric = GS()
print(test_metric.name)
test_metric.update_state([1, 1, 0, 0], [1, 1, 1, 0])
test_metric.result()

gs


<tf.Tensor: shape=(), dtype=float64, numpy=0.3333333333333333>

# Critical Success Index (CSI)

In [22]:
from imbal.metrics import CSI

test_metric = CSI()
print(test_metric.name)
test_metric.update_state([1, 1, 0, 0], [1, 1, 1, 0])
test_metric.result()

csi


<tf.Tensor: shape=(), dtype=float64, numpy=0.6666666666666666>